
#' Create concise chat content
#'
#' @param var character vector, list of variables from specs 
#' @param instruction character vector, list of instruction from specs
#'
#' @returns character vector, combined variable=instruction
specs_to_chat <- function(var, instruction){
  paste0("\n", var, "=", instruction)
}

#' Generate and clean R code based on specs' instructions
#'
#' @inheritParams specs_to_chat
#'
#' @returns R code
#' @example generate_code(specs$variable_name, specs$instruction)
generate_code <- function(var, instruction){
  
  # specs to chat
  qc_instruction <- specs_to_chat(var, instruction)
  
  # break down for next step
  qc_instruction <- paste(qc_instruction, collapse = ", ")
  
  ai_resp <- qc_wand$chat(
    glue::glue(
      "
Write executable R code to create an ADaM dataset. Use the following instruction, on the left side of the assignment is the variable name, and on the right side is the instruction how to create it: \n",
      qc_instruction
    )
  )
  
  rcode <- sub("^r\\n", "", strsplit(ai_resp, "```")[[1]][2])
  
  # insert the code into editor
  rstudioapi::insertText(rcode)
}

# 1. prepare a good data specification ----
# read in data specification
specs <- openxlsx2::read_xlsx("input/PopPK_TV_Analysis_Dataset_Specification.xlsx") |> 
  janitor::clean_names()

# 2. create a good prompt ----
#' Create the prompt containing some context info
#'
#' @param df_list named list, list of data frames to include their contents in the markdown
#'
#' @examples create_prompt(DM, EX, PC, LB)
create_prompt <- function(df_list){
  
  saveRDS(df_list, "inst/data_list.rds")
  
  rmarkdown::render("inst/sys-prompt.Rmd")
}

# source datasets
DM <- pharmaversesdtm::dm
LB <- pharmaversesdtm::lb
EX <- pharmaversesdtm::ex
PC <- pharmaversesdtm::pc

# pass a named list
create_prompt(list(
  DM = DM,
  EX = EX,
  PC = PC
))

# define system prompt for better response
qc_wand <- ellmer::chat_openai(
  system_prompt = "inst/sys-prompt.md"
)

# 3. ask AI to write code ----
# insert code that generated by AI
generate_code(specs$variable_name, specs$study_x_instruction)
library(dplyr)
library(lubridate)

# ---- 1. BL Variables from VS and LB Domains ----

# Weight and Height at Screening
vs_wtbl <- VS %>%
  filter(VSTESTCD == 'WEIGHT', VISIT == 'SCREENING') %>%
  select(USUBJID, WTBL = VSSTRESN)

vs_htbl <- VS %>%
  filter(VSTESTCD == 'HEIGHT', VISIT == 'SCREENING') %>%
  select(USUBJID, HTBL = VSSTRESN)

# Screening Laboratory
alb_bl <- LB %>% filter(LBTESTCD == 'ALB', VISIT == 'SCREENING') %>%
  select(USUBJID, ALBBL = LBSTRESN)
bili_bl <- LB %>% filter(LBTESTCD == 'BILI', VISIT == 'SCREENING') %>%
  select(USUBJID, BILIBL = LBSTRESN)

# All ALB and BILI test results
alb_t <- LB %>% filter(LBTESTCD == 'ALB') %>%
  select(USUBJID, ALBT = LBSTRESN, LBDTC)
bili_t <- LB %>% filter(LBTESTCD == 'BILI') %>%
  select(USUBJID, BILIT = LBSTRESN, LBDTC)

# ---- 2. Dosing Periods from EX ----

# Minimum start date (first dose) and maximum end date (last dose)
ex_doses <- EX %>%
  filter(!is.na(EXTRT) & EXTRT != "") %>%
  group_by(USUBJID) %>%
  summarise(
    TRTSDT = min(EXSTDTC, na.rm=TRUE),
    TRTEDT = max(EXENDTC, na.rm=TRUE)
  )

# Prepare dose-level data
ex_data <- EX %>%
  filter(!is.na(EXTRT) & EXTRT != "") %>%
  mutate(
    DATTM = EXSTDTC,
    EVID = 1,
    DOSE = EXDOSE,
    ACTTIME = NA_real_
  ) %>%
  select(USUBJID, DATTM, DOSE, EVID, ACTTIME, EXSTDTC)

# ---- 3. Observation Records (PC) ----

pc_data <- PC %>%
  filter(PCTESTCD == 'ANALYTE') %>%
  mutate(
    DATTM = PCDTC,
    EVID = 0,
    CONC = PCSTRESN,
    LLOQ = PCLLOQ,
    BLQ = if_else(!is.na(CONC) & !is.na(LLOQ) & CONC < LLOQ, 1L, 0L),
    DOSE = NA_real_,
    DV = CONC,
    ACTTIME = as.numeric(gsub(".*?(\\d+\\.?\\d*).*", "\\1", PCTPT)), # extract numeric from PCTPT
    MDV = if_else(is.na(CONC) | BLQ == 1, 1L, 0L)
  ) %>%
  select(USUBJID, DATTM, CONC, LLOQ, BLQ, DOSE, DV, MDV, ACTTIME, EVID, PCDTC)

# ---- 4. Combine Dosing and Observation Records ----
adam <- bind_rows(
  ex_data %>% mutate(COCONC = NA_real_, LLOQ = NA_real_, BLQ = NA_integer_, DV = NA_real_, MDV = NA_integer_),
  pc_data
) %>%
  arrange(USUBJID, as.POSIXct(DATTM, format="%Y-%m-%dT%H:%M:%S")) # sort by subject and datetime

# ---- 5. Calculate First Dose Time per Subject ----
first_dose_times <- adam %>%
  filter(EVID == 1) %>%
  group_by(USUBJID) %>%
  summarise(FIRST_DOSE_DATTM = min(as.POSIXct(DATTM, format="%Y-%m-%dT%H:%M:%S"), na.rm=TRUE))

adam <- adam %>%
  left_join(first_dose_times, by = "USUBJID") %>%
  mutate(
    TAFD = if_else(!is.na(DATTM) & !is.na(FIRST_DOSE_DATTM),
                   as.numeric(difftime(as.POSIXct(DATTM, format="%Y-%m-%dT%H:%M:%S"), FIRST_DOSE_DATTM, units = "hours")),
                   NA_real_)
  )

# ---- 6. Add Demographics and Derived Variables ----
adam <- adam %>%
  left_join(DM %>% select(USUBJID, STUDYID, SUBJID, SEX, AGE, RACE, ARM), by = "USUBJID") %>%
  left_join(vs_wtbl, by = "USUBJID") %>%
  left_join(vs_htbl, by = "USUBJID") %>%
  left_join(ex_doses, by = "USUBJID") %>%
  left_join(alb_bl, by = "USUBJID") %>%
  left_join(bili_bl, by = "USUBJID")

# ---- 7. Merge ALBT and BILIT by date if desired, otherwise keep as long variables ----
# For simplicity, merge latest prior lab for each record if required
adam <- adam %>%
  left_join(
    alb_t %>% rename(LB_DATE = LBDTC, ALBT = ALBT),
    by = "USUBJID"
  ) %>%
  left_join(
    bili_t %>% rename(LB_DATE = LBDTC, BILIT = BILIT),
    by = c("USUBJID", "LB_DATE")
  )

# ---- 8. Select and order the ADaM Variables as requested ----
adam <- adam %>%
  select(
    STUDYID, USUBJID, SUBJID, SEX, AGE, WTBL, HTBL, RACE, ARM, TRTSDT, TRTEDT,
    DATTM, ACTTIME, TAFD, CONC, LLOQ, BLQ, DOSE, DV, MDV, EVID, 
    ALBBL, BILIBL, ALBT, BILIT
  )

# ---- 9. Resulting ADaM ----
# Preview the result
head(adam)
