
# create concise chat content
specs_to_chat <- function(var, instruction){
  paste0("\n", var, "=", instruction)
}

# generate and clean R code based on specs' instructions
generate_code <- function(var, instruction){
  
  # specs to chat
  qc_instruction <- specs_to_chat(var, instruction)
  
  # break down for next step
  qc_instruction <- paste(qc_instruction, collapse = ", ")
  
  ai_resp <- qc_wand$chat(
    glue::glue(
      "
Write executable R code to create an Analysis Ready Dataset. Use the following instruction, on the left side of the assignment is the variable name, and on the right side is the instruction how to create it: \n",
      qc_instruction
    )
  )
  
  rcode <- sub("^r\\n", "", strsplit(ai_resp, "```")[[1]][2])
  
  # insert the code into editor
  rstudioapi::insertText(rcode)
}

# 1. prepare a good data specification ----
# read in data specification
specs <- openxlsx2::read_xlsx("input/PopPK_TV_Analysis_Dataset_Specification.xlsx") |> 
  janitor::clean_names()

# 2. create a good prompt ----
# create the prompt containing some context info -----
create_prompt <- function(df_list){
  
  saveRDS(df_list, "inst/data_list.rds")
  
  rmarkdown::render("inst/sys-prompt.Rmd")
  
  # Read and parse the HTML
  library(xml2)
  library(rvest)
  html <- read_html("inst/sys-prompt.html")
  
  # Remove <script> and <style> nodes
  xml_find_all(html, ".//script") |> xml_remove()
  xml_find_all(html, ".//style")  |> xml_remove()
  
  # Extract and return only the body text
  html |> 
    html_element("body") |> 
    html_text2()
}

# source datasets
DM <- pharmaversesdtm::dm
LB <- pharmaversesdtm::lb
EX <- pharmaversesdtm::ex
PC <- pharmaversesdtm::pc

prompt <- create_prompt(list(
  DM = DM,
  PC = PC
))

# define system prompt for better response
qc_wand <- ellmer::chat_openai(
  system_prompt = cat(prompt)
)

# 3. ask AI to write code ----
# insert code that generated by AI
generate_code(specs$variable_name, specs$study_x_instruction)